models:
  - name: rides_with_multiple_passengers
    description: '{{ doc("rides_with_multiple_passengers") }}'
    config:
      contract:
        enforced: true
    columns:
      - name: vendor_id
        data_type: string
        constraints:
            - type: not_null
      - name: pickup_datetime
        data_type: timestamp
        constraints:
            - type: not_null
      - name: dropoff_datetime
        data_type: timestamp
        constraints:
            - type: not_null
      - name: passenger_count
        data_type: int64
        constraints:
            - type: not_null
      - name: trip_distance
        data_type: numeric
        constraints:
            - type: not_null
      - name: rate_code
        data_type: string
        constraints:
            - type: not_null
      - name: store_and_fwd_flag
        data_type: string
        constraints:
            - type: not_null
      - name: payment_type
        data_type: string
        constraints:
            - type: not_null
      - name: fare_amount
        data_type: numeric
        constraints:
            - type: not_null
      - name: extra
        data_type: numeric
        constraints:
            - type: not_null
      - name: mta_tax
        data_type: numeric
        constraints:
            - type: not_null
      - name: tip_amount
        data_type: numeric
        constraints:
            - type: not_null
      - name: tolls_amount
        data_type: numeric
        constraints:
            - type: not_null
      - name: imp_surcharge
        data_type: numeric
        constraints:
            - type: not_null
      - name: airport_fee
        data_type: numeric
        constraints:
            - type: not_null
      - name: total_amount
        data_type: numeric
        constraints:
            - type: not_null
      - name: pickup_location_id
        data_type: string
        constraints:
            - type: not_null
      - name: dropoff_location_id
        data_type: string
        constraints:
            - type: not_null
      - name: data_file_year
        data_type: int64
        constraints:
            - type: not_null
      - name: data_file_month
        data_type: int64
        constraints:
            - type: not_null